### ISSUE TITLE
[Documentation] Deploy Claraverse as local network service

### ISSUE THREAD

**Issue by deckyfx** [badboysm890/ClaraVerse#77]
## Why?
1. I prefer to selfhost services like this as web application instead of desktop application
2. I want my services can be accessed from anywhere (in my local network), and in the future perhaps exposes it to world using cloudflare tunnel

## The Issues
1. It seems currently ClaraVerse assume that the service must be access locally only using localhost / 127.0.01 (CMIIW), so if accessed from another IP, it will throw many errors about CORS and wrong listened IP binded
2. I can not find any comphresible documentation to kickstart the service from github repo

## Scenario
- I wants to deploy claraverse services in my mac mini m4, 
- I already successed deploying ollama and openweb-ui there, let say it's IP is 192.168.0.103
- I want to access it from my windows laptop

## Requirement
- Docker
- Good editor to help your life
- Supabase account
- Time and a litle efforts

### 3. Decide 4 ports to be used, (i prefer to organize my opened ports) (let say: 5010, 5011, 5012, 5013)
   - 5010 will be the claraverse frontend
   - 5011 will be claraverse backend
   - 5012 will be claraverse interpreter
   - 5013 will be n8n

**Note**: n8n is extra service and is not part of claraverse repo, but claraverse does depends on it, you can run it as part of claraverse stack, or you may want to run it in different stack, and we can set it later within claraverse

**Note**: Technically you also need to reserve port for the ollama service, but in my case it is in another stack, and we can set it later within claraverse
### 4.  Modify some files
Assuming you are in claraverse directory, in `./vite.config.ts`, Add server config like this
```javascript
...
resolve: {
  alias: {
    '@': path.resolve(__dirname, './src'),
  },
},
server: {
  host: '0.0.0.0', // This tell vite to listen requests from any ip
}
```
### 6. Go to your supabase account, login or register, then go to `https://supabase.com/dashboard/project/ndvwkkgypamopmrydrhs/settings/api`, get your url, and api keys and put them in the `.env`
```text
VITE_SUPABASE_URL=your_supabase_url_here
VITE_SUPABASE_ANON_KEY=your_anon_key_here (anon public)
VITE_SUPABASE_SERVICE_KEY=your_service_key_here_server_only (service_role secret)
```
### 7.  edit `./Dockerfile` we need to set new commands to tell the Docker during build to accept some arguments passed via `.env` that we already set, add these lines
```text
...
# Declare build arguments to receive values from docker-compose.yml
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_KEY

# Set them as environment variables during the build process
# This makes them available when npm run build runs
ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
ENV VITE_SUPABASE_SERVICE_KEY=${VITE_SUPABASE_SERVICE_KEY}

RUN npm run build
...
```

### 8.  edit `src/services/api.js`, find line with this code 
```typescript
const ports = [8099, 8100, 8098, 8097, 8000, 8080];
```
add your port for claraverse backend, or in this example 5011, add it as the first element of array
```typescript
const ports = [5011, 8099, 8100, 8098, 8097, 8000, 8080]; # Like this
```
### 11. edit in `src/components/assistant_components/OnboardingModal.tsx` around line 88 set ip and port for n8m service or in this example `http://192.168.0.103:5013` like this
```typescript
const defaultApiConfig: APIConfig = {
    api_type: 'ollama',
    ollama_base_url: 'http://localhost:11434', // may also want to set this to your ollama address and port
    openai_base_url: 'https://api.openai.com/v1',
    openai_api_key: '',
    comfyui_base_url: 'http://localhost:8188', 
    n8n_base_url: 'http://192.168.0.103:5013', // this part 
    n8n_api_key: ''
  };
```
### 12. create `./docker-compose.yml` this will be our main entrypoint to kickstart the services
```yml
services:
  # Frontend service (Vite/React + Nginx)
  frontend:
    container_name: claraverse-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      args: # Pass these arguments during the build process
        VITE_SUPABASE_URL: "${VITE_SUPABASE_URL}"
        VITE_SUPABASE_ANON_KEY: "${VITE_SUPABASE_ANON_KEY}"
        VITE_SUPABASE_SERVICE_KEY: "${VITE_SUPABASE_SERVICE_KEY}"
    ports:
      - "5010:8069" # Map host port 5010 to container port 8069 (as exposed by Nginx)
    depends_on:
      - backend # Ensure backend starts before frontend

  # Backend service (Python)
  backend:
    container_name: claraverse-backend
    build:
      context: ./py_backend
      dockerfile: Dockerfile
    ports:
      - "5011:5000" # Map host port 5011 to container port 5000 (as exposed by Python backend)
    volumes:
      - ./data/backend:/root/.clara

  interpreter:
    container_name: claraverse-interpreter
    image: clara17verse/clara-interpreter:latest
    ports:
      - "5012:8000" # Map host port 5012to container port 8000
    volumes:
      - ./data/interpreter:/app/data

  n8n:
    container_name: clara-n8n
    image: n8nio/n8n 
    ports:
      - "5013:5678"           # Host port 5013 mapped to container port 5678
    environment:
      N8N_SECURE_COOKIE: false
    volumes:
      - ./data/n8n_data:/home/node/.n8n

```

### 13. Build all images
run in terminal
```bash
docker-compose build
```
As long as you make no further file edit, you only need to run this once, but eveytime you make changes, you need to rebuild the images 

### 14. Run the service with command
```bash
docker-compose up
```
